### ISSUE TITLE
some dependent assembly are missing in release binary.

### ISSUE THREAD

**Issue by itn3000** [allisterb/jemalloc.NET#4]
I downloaded jemalloc.NET-0.1.1 from [releases](https://github.com/allisterb/jemalloc.NET/releases/download/v0.1.1/jemalloc.NET-win-msvc-0.1.1.zip), and I tried to do the "jembench.cmd".
I expect to begin the benchmark program, but I got the following error message;
```
Error:
  An assembly specified in the application dependencies manifest (jemalloc.Cli.deps.json) was not found:
    package: 'BenchmarkDotNet.Core', version: '0.10.11'
    path: 'lib/netcoreapp2.0/BenchmarkDotNet.Core.dll'
```
I think this error might be  pointing out missing assembly(by PackageReference?).

**Comment by allisterb** [comment]
Oh yes it's just missing the dependent assemblies. It probably didn't happen on my machines because I have the needed assemblies cached somewhere. I''ll make another patch release to fix this today.

**Comment by allisterb** [comment]
Could you try: https://github.com/allisterb/jemalloc.NET/releases/tag/v0.1.3

**Comment by itn3000** [comment]
Thank you for fixing. It seems to be almost OK.
But in jembench.bat, it should be `dotnet .\x64\Release\jemalloc.Cli.dll %*` instead of `dotnet .\x64\Release\netcoreapp2.0\jemalloc.Cli.dll %*`

**Comment by allisterb** [comment]
Sorry I suck :( made a new build with the correct path: https://github.com/allisterb/jemalloc.NET/releases/tag/v0.1.3. Thanks for testing this; I have to fix my build process.

**Comment by itn3000** [comment]
I retried and seemed to be fine.
Thank you for fixing.
